name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 500

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.10.2
      uses: actions/setup-python@v4  # Ensure you are using @v4
      with:
        python-version: '3.10.2'  # Specify the full version of Python

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests
