name: Python Package CI

on: 
  push: 
    branches: 
      - main
  pull_request: 
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 500  # Increase this value as needed
    
    strategy:
      matrix:
        python-version: [3.12.7,3.11.7,3.9.7]  # List the Python versions you want to test

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest tests
