name: Publish Package

on:
  release:
    types: [published]  # Triggers when a release is published

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  # Change to your desired Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine  # Ensure you have the necessary tools

    - name: Build the package
      run: |
        python setup.py sdist bdist_wheel

    - name: Configure OpenID Connect
      id: oidc
      run: |
        echo "TWINE_USERNAME=__token__" >> $GITHUB_ENV
        echo "TWINE_PASSWORD=${{ secrets.PYPI_TOKEN }}" >> $GITHUB_ENV

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: ${{ env.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ env.TWINE_PASSWORD }}
      run: |
        twine upload dist/*
